-- Add slide thumbnail paths to business_case_templates
-- Thumbnails are pre-rendered PNG images stored in Supabase Storage
-- Generated by the generate-slide-thumbnails edge function via ConvertAPI
ALTER TABLE business_case_templates
  ADD COLUMN IF NOT EXISTS thumbnail_paths TEXT[] DEFAULT NULL;

-- Allow PNG thumbnails in bc-templates bucket (previously only allowed PPTX)
UPDATE storage.buckets
SET allowed_mime_types = ARRAY[
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'image/png',
  'image/jpeg'
]
WHERE id = 'bc-templates';
