-- =====================================================
-- 070: Seed skill_registry with existing Chief skills
-- =====================================================

INSERT INTO public.skill_registry (name, display_name, description, category, skill_definition, requires_integrations, is_system)
VALUES
  ('buscar_prospectos', 'Buscar Prospectos', 'Busca prospectos en una empresa usando LinkedIn Sales Navigator (L1→L2→L3).', 'sales', 'Calls cascade-search-company edge function. Params: org_id, company_name, titles[], seniority_levels[], limit, buyer_persona_id.', ARRAY['unipile'], true),
  ('crear_cadencia', 'Crear Cadencia', 'Crea una cadencia de outreach con pasos multicanal (LinkedIn + email).', 'sales', 'Creates cadence + steps via Supabase REST. Params: org_id, name, description, steps[{step_number, step_type, delay_days, template, subject}].', '{}', true),
  ('descubrir_empresas', 'Descubrir Empresas', 'Descubre empresas que encajan con el ICP por industria, tamaño, ubicación.', 'sales', 'Calls discover-icp-companies edge function. Params: org_id, icp_profile_id, criteria{industries, employee_range, revenue_range, locations, technologies}, limit.', '{}', true),
  ('investigar_empresa', 'Investigar Empresa', 'Investiga una empresa a fondo — noticias, tech stack, competidores, insights.', 'sales', 'Calls company-research edge function. Params: org_id, company_name, company_domain, depth (quick/deep).', ARRAY['firecrawl'], true),
  ('enriquecer_prospectos', 'Enriquecer Prospectos', 'Enriquece un prospecto con email verificado, teléfono y datos de LinkedIn.', 'sales', 'Calls enrich-prospect edge function. Params: org_id, prospect_id or (first_name + last_name + company).', ARRAY['unipile'], true),
  ('ver_actividad', 'Ver Actividad', 'Consulta el log de actividades — mensajes enviados, respuestas, errores.', 'sales', 'Queries activity_log table via Supabase REST. Params: org_id, lead_id, cadence_id, activity_type, status, date_from, limit.', '{}', true),
  ('enviar_mensaje', 'Enviar Mensaje LinkedIn', 'Envía un mensaje directo, InMail o solicitud de conexión por LinkedIn.', 'sales', 'Calls linkedin-send-message edge function. Params: org_id, sender_account_id, recipient_provider_id, message, message_type (message/inmail/connection_request).', ARRAY['unipile'], true),
  ('business_case', 'Business Case', 'Genera un business case personalizado para una empresa.', 'sales', 'Calls generate-business-case edge function. Params: org_id, company_name, company_domain, prospect_name, prospect_title, pain_points[], language.', '{}', true),
  ('ver_metricas', 'Ver Métricas', 'Consulta métricas de cadencias — tasas de respuesta, conexión, conversión.', 'sales', 'Queries cadence metrics via Supabase REST aggregations. Params: org_id, cadence_id, date_from, date_to.', '{}', true),
  ('gestionar_leads', 'Gestionar Leads', 'CRUD sobre leads — listar, crear, actualizar, asignar a cadencias.', 'sales', 'CRUD on leads table via Supabase REST. Operations: list, create, update, assign_to_cadence, remove_from_cadence. Params: org_id, operation, lead, lead_id, cadence_id.', '{}', true),
  ('guardar_sesion', 'Guardar Sesión', 'Guarda la identidad del usuario asociada a su número de WhatsApp.', 'system', 'Upserts whatsapp_sessions or chief_sessions table. Params: whatsapp_number, org_id, user_id, member_id, display_name.', '{}', true),
  ('identificar_usuario', 'Identificar Usuario', 'Busca un usuario dentro de una organización por su email.', 'system', 'Queries profiles + organization_members by email and org_id. Returns user_id, member_id, display_name, connected accounts.', '{}', true),
  ('enviar_otp', 'Enviar OTP', 'Envía un código de verificación de 6 dígitos al email del usuario.', 'system', 'Calls Supabase Auth OTP endpoint. Params: email.', '{}', true),
  ('verificar_otp', 'Verificar OTP', 'Verifica el código OTP y establece la sesión permanente del usuario.', 'system', 'Verifies OTP via Supabase Auth, then identifies user and saves session. Params: email, token, org_id, whatsapp_number.', '{}', true),
  ('enviar_email', 'Enviar Email', 'Envía un email usando la cuenta Gmail conectada del usuario.', 'sales', 'Calls send-email edge function. Params: org_id, owner_id, to, subject, body, lead_id, cc.', ARRAY['gmail'], true),
  ('gestionar_prompts', 'Gestionar AI Prompts', 'CRUD sobre AI prompts — listar, ver, crear, actualizar, eliminar.', 'sales', 'CRUD on ai_prompts table via Supabase REST. Operations: list, get, create, update, delete. Params: org_id, owner_id, operation, prompt_id, prompt{}.', '{}', true),
  ('gestionar_templates', 'Gestionar Templates', 'CRUD sobre templates de mensajes — listar, ver, crear, actualizar, eliminar.', 'sales', 'CRUD on templates table via Supabase REST. Operations: list, get, create, update, delete. Params: org_id, owner_id, operation, template_id, template{}.', '{}', true),
  ('gestionar_personas', 'Gestionar Buyer Personas', 'CRUD sobre buyer personas — listar, ver, crear, actualizar, eliminar.', 'sales', 'CRUD on buyer_personas table via Supabase REST. Operations: list, get, create, update, delete. Params: org_id, owner_id, operation, persona_id, persona{}.', '{}', true),
  ('gestionar_perfiles_icp', 'Gestionar Perfiles ICP', 'CRUD sobre perfiles ICP — listar, ver, crear, actualizar, eliminar.', 'sales', 'CRUD on icp_profiles table via Supabase REST. Operations: list, get, create, update, delete. Params: org_id, owner_id, operation, profile_id, profile{}.', '{}', true),
  ('ver_notificaciones', 'Ver Notificaciones', 'Ver notificaciones (respuestas, errores, emails abiertos) y marcar como leídas.', 'sales', 'Queries notifications table. Operations: list, mark_read, mark_all_read. Params: org_id, owner_id, operation, notification_id, filters{}.', '{}', true),
  ('ver_cadencia_detalle', 'Ver Detalle Cadencia', 'Ve los detalles completos de una cadencia: pasos, leads asignados, estado.', 'sales', 'Queries cadences + cadence_steps + cadence_leads via Supabase REST. Params: org_id, cadence_id.', '{}', true),
  ('ver_conexiones', 'Ver Conexiones', 'Ve las cuentas conectadas del usuario (LinkedIn, Gmail, etc.).', 'sales', 'Queries unipile_accounts + ae_integrations via Supabase REST. Params: org_id, user_id.', ARRAY['unipile'], true),
  ('ver_programacion', 'Ver Programación', 'Ve las acciones programadas — próximos envíos, estado.', 'sales', 'Queries schedules table via Supabase REST. Params: org_id, cadence_id, status, limit.', '{}', true),
  ('capturar_pantalla', 'Capturar Pantalla', 'Captura un screenshot del dashboard de Chief.', 'system', 'Generates magic link + calls Firecrawl to screenshot page. Params: page_path, user_email, wait_ms.', ARRAY['firecrawl'], true),
  ('ver_calendario', 'Ver Calendario', 'Ve los eventos del calendario del usuario para un rango de fechas.', 'sales', 'Queries ae_activities (type=meeting) via Supabase REST. Params: user_id, org_id, date_from, date_to.', ARRAY['google_calendar'], true),
  ('buscar_slots_disponibles', 'Buscar Slots Disponibles', 'Busca slots de tiempo libre en el calendario del usuario.', 'sales', 'Calls ae-calendar-free-slots edge function. Params: user_id, org_id, date, days, timezone, business_start, business_end.', ARRAY['google_calendar'], true),
  ('crear_evento_calendario', 'Crear Evento Calendario', 'Crea un evento en Google Calendar y envía invitaciones por email.', 'sales', 'Calls ae-calendar-create-event edge function. Params: user_id, org_id, title, start_datetime, end_datetime, timezone, description, location, attendees[].', ARRAY['google_calendar'], true),
  ('sincronizar_calendario', 'Sincronizar Calendario', 'Sincroniza el calendario del usuario con Google Calendar.', 'sales', 'Calls ae-calendar-sync edge function. Params: user_id, org_id.', ARRAY['google_calendar'], true)
ON CONFLICT (name) DO NOTHING;
