/* ============================================================
   Yuno SDR Business Case Deck — Slides 1-8
   Nova-light redesign (2026-05-14) · trilingual 2026-05-18

   01 Cover · 02 Agenda
   03 Section: Context  · 04 Client Stack · 05 Geography
   06 Section: Why Yuno · 07 Yuno Overview · 08 Trusted By

   All slides read from `data` prop = window.DECK_DEFAULTS injected
   by sdr-bc-render. Math is upstream; here we only surface fields.

   Language: every slide reads `data.language` (defaulted to 'en' by
   the render function) and pulls copy from window.SDR_BC_I18N via the
   window.tr / window.trf helpers loaded by /sdr-bc-assets/sdr-bc-i18n.js.
   Currency: `data.currency` (defaulted to 'USD'). Slides do NOT format
   raw USD numbers themselves — the pre-formatted *_M / *TOT strings
   from the edge function are intentionally currency-symbol-free so the
   slide can prepend the right symbol based on `currency`. Build-cost
   numbers in the dev table are still rendered with a literal $ because
   they are raw USD values (and currency conversion is explicitly out of
   scope per plan-presentations-multilingual.md).
   ============================================================ */

// Resolver — picks the active language from data.language with safe fallback.
function pickLang(data) {
  const l = data && data.language;
  return (l === 'es' || l === 'pt' || l === 'en') ? l : 'en';
}
function pickCurrency(data) {
  return (data && typeof data.currency === 'string' && data.currency) || 'USD';
}

// =============================================================================
// World-map pin coordinates — % of the 2:1 map container.
// world-map.svg is an EQUAL EARTH projection (central meridian 0°) stretched
// to its 2000×1000 viewBox — NOT equirectangular. Each entry was generated by
// projecting the country's visual-center anchor through the Equal Earth
// forward equations fitted to this SVG, then verified point-in-polygon
// against the SVG's land paths (coastal anchors snapped ≤0.9% onto the drawn
// landmass). Regenerate with the same script if world-map.svg ever changes —
// do NOT hand-tweak.
// Keys match SimilarWeb's `country_name` spelling; common variants ("UK",
// "USA", "Korea"…) are folded in via COUNTRY_NAME_ALIASES. Unknown countries
// still appear in the side list but won't show a pin on the map.
// =============================================================================
const SVG_COUNTRY_COORDS = {
  // Americas
  'United States':       { x: 25.65, y: 20.93 },
  'Canada':              { x: 26.95, y: 10.81 },
  'Mexico':              { x: 22.69, y: 31.98 },
  'Brazil':              { x: 35.67, y: 58.05 },
  'Argentina':           { x: 33.48, y: 75.67 },
  'Chile':               { x: 31.64, y: 73.21 },
  'Colombia':            { x: 29.75, y: 46.54 },
  'Peru':                { x: 29.18, y: 57.67 },
  'Ecuador':             { x: 28.23, y: 51.15 },
  'Venezuela':           { x: 31.74, y: 44.24 },
  'Uruguay':             { x: 35.64, y: 74.48 },
  'Paraguay':            { x: 34.41, y: 67.65 },
  'Bolivia':             { x: 32.39, y: 62.74 },
  'Costa Rica':          { x: 26.78, y: 42.53 },
  'Panama':              { x: 27.97, y: 43.48 },
  'Guatemala':           { x: 25.30, y: 38.54 },
  'Dominican Republic':  { x: 31.00, y: 35.61 },
  'Puerto Rico':         { x: 31.80, y: 36.13 },
  'Jamaica':             { x: 28.84, y: 36.20 },
  'Honduras':            { x: 26.33, y: 38.69 },
  'El Salvador':         { x: 25.65, y: 39.44 },
  'Nicaragua':           { x: 26.62, y: 40.30 },
  'Trinidad and Tobago': { x: 32.81, y: 42.03 },
  'Bahamas':             { x: 28.87, y: 31.76 },
  // EMEA
  'United Kingdom':      { x: 49.66, y: 12.62 },
  'Ireland':             { x: 48.22, y: 12.39 },
  'Spain':               { x: 49.11, y: 20.47 },
  'Portugal':            { x: 48.03, y: 20.87 },
  'France':              { x: 50.56, y: 16.34 },
  'Germany':             { x: 52.32, y: 13.73 },
  'Netherlands':         { x: 51.24, y: 12.96 },
  'Belgium':             { x: 51.07, y: 13.91 },
  'Italy':               { x: 53.07, y: 18.76 },
  'Switzerland':         { x: 51.93, y: 16.22 },
  'Austria':             { x: 53.39, y: 15.79 },
  'Sweden':              { x: 53.18, y:  7.69 },
  'Norway':              { x: 51.81, y:  7.94 },
  'Denmark':             { x: 52.02, y: 10.81 },
  'Finland':             { x: 55.28, y:  7.26 },
  'Poland':              { x: 54.37, y: 13.02 },
  'Czech Republic':      { x: 53.56, y: 14.38 },
  'Slovakia':            { x: 54.51, y: 15.05 },
  'Hungary':             { x: 54.54, y: 15.97 },
  'Romania':             { x: 55.91, y: 16.78 },
  'Greece':              { x: 55.43, y: 20.93 },
  'Turkey':              { x: 58.67, y: 21.27 },
  'Russia':              { x: 60.67, y:  9.73 },
  'UAE':                 { x: 64.46, y: 31.91 },
  'Saudi Arabia':        { x: 61.85, y: 31.83 },
  'Qatar':               { x: 63.57, y: 30.88 },
  'Kuwait':              { x: 62.41, y: 27.99 },
  'Bahrain':             { x: 63.34, y: 30.37 },
  'Oman':                { x: 65.19, y: 34.04 },
  'Jordan':              { x: 59.41, y: 26.64 },
  'Israel':              { x: 59.13, y: 26.50 },
  'Lebanon':             { x: 59.23, y: 24.75 },
  'Egypt':               { x: 57.86, y: 30.01 },
  'South Africa':        { x: 56.43, y: 72.15 },
  'Nigeria':             { x: 52.21, y: 42.71 },
  'Kenya':               { x: 60.50, y: 49.62 },
  'Morocco':             { x: 48.43, y: 26.22 },
  'Ghana':               { x: 49.67, y: 43.94 },
  'Ivory Coast':         { x: 48.48, y: 44.24 },
  'Tanzania':            { x: 59.67, y: 54.92 },
  'Tunisia':             { x: 52.42, y: 24.61 },
  'Ethiopia':            { x: 60.94, y: 43.40 },
  'Algeria':             { x: 50.68, y: 28.93 },
  // APAC
  'India':               { x: 71.18, y: 33.30 },
  'Pakistan':            { x: 67.84, y: 27.85 },
  'Bangladesh':          { x: 74.03, y: 31.98 },
  'Sri Lanka':           { x: 72.52, y: 44.17 },
  'China':               { x: 76.18, y: 24.33 },
  'Hong Kong':           { x: 80.58, y: 33.08 },
  'Taiwan':              { x: 82.65, y: 32.05 },
  'South Korea':         { x: 82.32, y: 22.85 },
  'Japan':               { x: 84.99, y: 23.30 },
  'Singapore':           { x: 78.83, y: 48.96 },
  'Malaysia':            { x: 78.50, y: 46.80 },
  'Thailand':            { x: 77.57, y: 38.16 },
  'Vietnam':             { x: 78.37, y: 34.04 },
  'Indonesia':           { x: 81.53, y: 50.38 },
  'Philippines':         { x: 83.43, y: 37.93 },
  'Australia':           { x: 85.61, y: 68.53 },
  'New Zealand':         { x: 91.50, y: 81.37 },
};

// Variants seen from SimilarWeb / LLM top_markets fallback → canonical
// SVG_COUNTRY_COORDS / NAME_TO_ISO keys. Lookup keys are lowercased with
// periods/commas stripped (so "U.S.A." → 'usa'). Mirrors the variant list in
// supabase/functions/_shared/regions.ts NAME_TO_ISO_MAP.
const COUNTRY_NAME_ALIASES = {
  'uk': 'United Kingdom', 'gb': 'United Kingdom', 'great britain': 'United Kingdom', 'england': 'United Kingdom',
  'usa': 'United States', 'us': 'United States', 'united states of america': 'United States', 'estados unidos': 'United States',
  'korea': 'South Korea', 'korea south': 'South Korea', 'republic of korea': 'South Korea',
  'united arab emirates': 'UAE',
  'viet nam': 'Vietnam',
  'czechia': 'Czech Republic',
  'türkiye': 'Turkey', 'turkiye': 'Turkey',
  'brasil': 'Brazil', 'méxico': 'Mexico', 'perú': 'Peru', 'panamá': 'Panama',
  'españa': 'Spain', 'italia': 'Italy',
  'the netherlands': 'Netherlands', 'holland': 'Netherlands',
  'ksa': 'Saudi Arabia',
  'republica dominicana': 'Dominican Republic', 'república dominicana': 'Dominican Republic',
  "cote d'ivoire": 'Ivory Coast', 'côte d’ivoire': 'Ivory Coast',
  'the bahamas': 'Bahamas',
  'trinidad & tobago': 'Trinidad and Tobago',
  'hong kong sar': 'Hong Kong',
  'russian federation': 'Russia',
};

// Case-insensitive index over the canonical keys ("united kingdom" → "United Kingdom").
const SVG_COUNTRY_KEY_BY_LOWER = Object.keys(SVG_COUNTRY_COORDS)
  .reduce((acc, k) => { acc[k.toLowerCase()] = k; return acc; }, {});

function normalizeCountryName(name) {
  const raw = String(name || '').trim();
  if (SVG_COUNTRY_COORDS[raw]) return raw;
  const k = raw.toLowerCase().replace(/[.,]/g, '');
  return COUNTRY_NAME_ALIASES[k] || SVG_COUNTRY_KEY_BY_LOWER[k] || raw;
}

function svgCoordsFor(country) {
  return SVG_COUNTRY_COORDS[normalizeCountryName(country)] || null;
}

const NAME_TO_ISO = {
  'United States':'US','Canada':'CA','Mexico':'MX','Brazil':'BR','Argentina':'AR',
  'Chile':'CL','Colombia':'CO','Peru':'PE','Ecuador':'EC','Venezuela':'VE',
  'Uruguay':'UY','Paraguay':'PY','Bolivia':'BO','Costa Rica':'CR','Panama':'PA',
  'Guatemala':'GT','Dominican Republic':'DO','Puerto Rico':'PR','Jamaica':'JM',
  'Honduras':'HN','El Salvador':'SV','Nicaragua':'NI','Trinidad and Tobago':'TT',
  'Bahamas':'BS',
  'United Kingdom':'UK','Ireland':'IE','Spain':'ES','Portugal':'PT','France':'FR',
  'Germany':'DE','Netherlands':'NL','Belgium':'BE','Italy':'IT','Switzerland':'CH',
  'Austria':'AT','Sweden':'SE','Norway':'NO','Denmark':'DK','Finland':'FI',
  'Poland':'PL','Czech Republic':'CZ','Slovakia':'SK','Hungary':'HU','Romania':'RO',
  'Greece':'GR','Turkey':'TR','Russia':'RU',
  'UAE':'AE','Saudi Arabia':'SA','Qatar':'QA','Kuwait':'KW','Bahrain':'BH',
  'Oman':'OM','Jordan':'JO','Israel':'IL','Lebanon':'LB','Egypt':'EG',
  'South Africa':'ZA','Nigeria':'NG','Kenya':'KE','Morocco':'MA','Ghana':'GH',
  'Ivory Coast':'CI','Tanzania':'TZ','Tunisia':'TN','Ethiopia':'ET','Algeria':'DZ',
  'India':'IN','Pakistan':'PK','Bangladesh':'BD','Sri Lanka':'LK','China':'CN',
  'Hong Kong':'HK','Taiwan':'TW','South Korea':'KR','Japan':'JP','Singapore':'SG',
  'Malaysia':'MY','Thailand':'TH','Vietnam':'VN','Indonesia':'ID','Philippines':'PH',
  'Australia':'AU','New Zealand':'NZ',
};

function isoFor(country) {
  const n = normalizeCountryName(country);
  return NAME_TO_ISO[n] || String(n || '').slice(0, 2).toUpperCase();
}

// =============================================================================
// Slide 01 — Cover
// =============================================================================
function Slide01Cover({ data }) {
  const lang = pickLang(data);
  const clientName = data.clientName || '{{client}}';
  const grandTotal = data.GRAND_TOTAL || '{{GRAND_TOTAL}}';
  const regionsCount = (Array.isArray(data.regions_rendered) && data.regions_rendered.length) || 4;

  return (
    <div className="slide theme-light" data-screen-label="01 Cover">
      {/* Ambient accent glow */}
      <div style={{
        position: 'absolute', top: '-10%', right: '-15%', width: '70%', height: '120%',
        background: 'radial-gradient(circle at 50% 50%, rgba(62,79,224,0.18) 0%, rgba(62,79,224,0) 60%)',
        animation: 'orbDrift 20s ease-in-out infinite', pointerEvents: 'none',
      }} />
      {/* Masked world-map silhouette in accent (matches Phase-0 preview) */}
      <div style={{
        position: 'absolute', top: '15%', right: '-8%', width: '55%', aspectRatio: '1/1',
        backgroundColor: 'var(--accent)',
        WebkitMaskImage: 'url(/sdr-bc-assets/world-map.svg)',
        maskImage: 'url(/sdr-bc-assets/world-map.svg)',
        WebkitMaskRepeat: 'no-repeat', maskRepeat: 'no-repeat',
        WebkitMaskSize: 'contain', maskSize: 'contain',
        WebkitMaskPosition: 'center', maskPosition: 'center',
        opacity: 0.16, pointerEvents: 'none', zIndex: 1,
      }} />

      {/* Topbar */}
      <div style={{ position: 'relative', zIndex: 5, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 24 }}>
          <span className="yuno-wordmark" style={{ fontSize: 34 }}>yuno</span>
          <span style={{ width: 1, height: 32, background: 'rgba(30,32,48,0.22)' }} />
          <span style={{
            fontFamily: 'var(--font-display)', fontSize: 32, fontWeight: 600,
            color: 'var(--ink-strong)', letterSpacing: '-0.02em',
          }}>{clientName}</span>
        </div>
        <div className="mono-kicker">
          <span className="caret">{'>'}</span>{window.tr(lang, 's01.mono_doc')} / {data.date || '2026'}
        </div>
      </div>

      {/* Body */}
      <div className="stagger" style={{
        position: 'relative', zIndex: 5, flex: 1,
        display: 'flex', flexDirection: 'column', justifyContent: 'center', maxWidth: '72%',
        '--stagger-base': '0.1s', '--stagger-step': '0.09s',
      }}>
        <MonoKicker beam beamDelay={2} style={{ marginBottom: 24 }}>{window.tr(lang, 's01.mono_kicker')}</MonoKicker>

        <h1 className="t-title t-title-xl">
          {/* Title is rendered as: head + <accent>middle</accent> + tail.
              EN preserves the original "Unify your payment\nstack," + <accent> + "annually." */}
          {window.tr(lang, 's01.title_head').split('\n').map((seg, i, arr) => (
            <React.Fragment key={i}>
              {seg}{i < arr.length - 1 ? <br/> : null}
            </React.Fragment>
          ))}{' '}
          <span className="accent">{window.trf(lang, 's01.title_accent', { grandTotal })}</span>{window.tr(lang, 's01.title_tail')}
        </h1>

        <p className="t-body-l" style={{ marginTop: 36, color: 'var(--ink-secondary)', maxWidth: 840 }}>
          {window.trf(lang, 's01.body', { clientName, regionsCount })}
        </p>
      </div>

      {/* Bottom meta strip */}
      <div style={{
        position: 'relative', zIndex: 5,
        display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end',
        marginTop: 'auto',
      }}>
        <div style={{ display: 'flex', gap: 56 }}>
          <div>
            <div className="mono-kicker" style={{ marginBottom: 8, textTransform: 'none' }}>{window.tr(lang, 's01.meta_prepared_by')}</div>
            <div style={{ fontSize: 18, fontWeight: 600, color: 'var(--ink-strong)' }}>
              {data.sdr_name || data.preparedBy || 'Yuno Sales Strategy'}
            </div>
            {data.sdr_position && (
              <div style={{ fontSize: 12, color: 'var(--ink-secondary)', marginTop: 2, letterSpacing: '0.01em' }}>
                {data.sdr_position}
              </div>
            )}
          </div>
        </div>
        <div style={{ fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--ink-faint)', letterSpacing: '0.1em' }}>
          01 / 28
        </div>
      </div>
    </div>
  );
}

// =============================================================================
// Slide 02 — Agenda
// =============================================================================
function Slide02Agenda({ data }) {
  const lang = pickLang(data);
  const clientName = data.clientName || '{{client}}';
  // 4 chapters in a 2×2 grid (matches Phase-0 preview). Chapter 04 = the
  // closing CTA, so the agenda fully represents the 27-slide layout instead
  // of folding "The Proposal" under Business Case.
  const items = ['01', '02', '03', '04'].map(n => ({
    n,
    title: window.tr(lang, `s02.items.${n}.title`),
    body:  window.trf(lang, `s02.items.${n}.body`, { clientName }),
  }));

  return (
    <div className="slide theme-light" data-screen-label="02 Agenda">
      <SlideChrome section={window.tr(lang, 'common.agenda')} pageNum={2} />

      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 36 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: 36 }}>
          <h2 className="t-title t-title-m" style={{ maxWidth: '66%' }}>
            {window.tr(lang, 's02.title_head')}<span className="accent">{window.tr(lang, 's02.title_accent')}</span>{window.tr(lang, 's02.title_tail')}
          </h2>
          <p className="t-body" style={{ maxWidth: '30%', textAlign: 'right', color: 'var(--ink-secondary)' }}>
            {window.trf(lang, 's02.subtitle', { clientName })}
          </p>
        </div>

        <MonoKicker beam beamDelay={1.5}>{window.tr(lang, 's02.mono_kicker')}</MonoKicker>

        <div className="stagger" style={{
          flex: 1, display: 'grid',
          gridTemplateColumns: 'repeat(2, 1fr)',
          gridTemplateRows: 'repeat(2, 1fr)',
          gap: 28,
          '--stagger-base': '0.15s', '--stagger-step': '0.1s',
        }}>
          {items.map((it, i) => (
            <div key={it.n} className="card-nova" style={{
              padding: 40, display: 'flex', flexDirection: 'column', gap: 18,
            }}>
              <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between' }}>
                <span style={{
                  fontFamily: 'var(--font-mono)', fontSize: 14,
                  color: 'var(--accent)', fontWeight: 600, letterSpacing: '0.04em',
                }}>{it.n}</span>
                <div style={{ flex: 1, marginLeft: 18 }}><BeamRule delay={i * 1.5} /></div>
              </div>
              <div style={{
                fontFamily: 'var(--font-display)', fontSize: 44, fontWeight: 500,
                letterSpacing: '-0.02em', color: 'var(--ink-strong)', lineHeight: 1.05,
              }}>
                {it.title}
              </div>
              <div style={{ fontSize: 17, color: 'var(--ink-secondary)', lineHeight: 1.5 }}>
                {it.body}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// =============================================================================
// Section divider (slides 03, 06, 09) — shared component, dark surface
// =============================================================================
function SectionDivider({ index, title, subtitle, pageNum, lang }) {
  const l = lang || 'en';
  return (
    <div className="slide theme-dark" data-screen-label={`${String(pageNum).padStart(2,'0')} Section · ${title}`}>
      <div style={{
        position: 'absolute', top: '15%', left: '-15%', width: '60%', height: '90%',
        background: 'radial-gradient(circle, rgba(62,79,224,0.28) 0%, rgba(62,79,224,0) 60%)',
        animation: 'orbDrift 24s ease-in-out infinite', pointerEvents: 'none',
      }} />
      <SlideChrome section={window.tr(l, 'common.agenda')} pageNum={pageNum} footer={`${window.tr(l, 'common.section')} ${index} · ${title}`} />

      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
        <MonoKicker
          beam beamDelay={1.5}
          beamProps={{ base: 'var(--beam-base-dark)', beam: 'var(--beam-bright-dark)' }}
          style={{ marginBottom: 28 }}
        >
          {window.tr(l, 'common.chapter')} / {index}
        </MonoKicker>

        <div className="t-number" style={{
          fontSize: 280, fontWeight: 200, color: 'rgba(255,255,255,0.16)',
          letterSpacing: '-0.05em', lineHeight: 0.8, marginBottom: 8,
        }}>
          {index}
        </div>
        <h2 className="t-title t-title-xl" style={{ color: '#fff', maxWidth: 1500 }}>
          {title}.
        </h2>
        <p className="t-body-l" style={{
          marginTop: 28, color: 'rgba(255,255,255,0.72)', maxWidth: 920,
        }}>
          {subtitle}
        </p>
      </div>
    </div>
  );
}

function Slide03ContextSection({ data }) {
  const lang = pickLang(data);
  return (
    <SectionDivider
      index="01"
      title={window.tr(lang, 's03.title')}
      subtitle={window.tr(lang, 's03.subtitle')}
      pageNum={3}
      lang={lang}
    />
  );
}

// =============================================================================
// Slide 04 — Client Payment Stack
// =============================================================================
function Slide04ClientStack({ data }) {
  const lang = pickLang(data);
  const clientName = data.clientName || '{{client}}';
  const acquirers = data.acquirers ?? ['Stripe', 'Adyen', 'Worldpay', 'Cybersource'];
  const gateways  = data.gateways  ?? ['Braintree', 'PayPal', 'dLocal'];
  const methods   = data.methods   ?? ['Visa', 'Mastercard', 'Amex', 'Apple Pay', 'Google Pay', 'PayPal'];
  // Default observations (fallback when stack_observations missing) — keyed for i18n.
  const defaultObservations = {
    es: [
      'Las redes de tarjetas dominan el volumen online en los mercados principales',
      'Cobertura limitada de APMs en regiones de alto crecimiento',
      'Múltiples integraciones a adquirentes locales crean complejidad operativa',
    ],
    en: [
      'Card networks dominate online volume across primary markets',
      'Limited APM coverage in high-growth regions',
      'Multiple local acquirer integrations create operational complexity',
    ],
    pt: [
      'Redes de cartões dominam o volume online nos principais mercados',
      'Cobertura limitada de APMs em regiões de alto crescimento',
      'Múltiplas integrações com adquirentes locais geram complexidade operacional',
    ],
  };
  const observations = data.stack_observations ?? defaultObservations[lang] ?? defaultObservations.en;

  return (
    <div className="slide theme-light" data-screen-label="04 Client Stack">
      <SlideChrome section={window.tr(lang, 'common.context_payment_stack')} pageNum={4} />

      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 28 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: 36 }}>
          <div>
            <MonoKicker beam={false} style={{ marginBottom: 14 }}>{window.tr(lang, 's04.mono_kicker')}</MonoKicker>
            <h2 className="t-title t-title-m">
              {window.trf(lang, 's04.title_h_es', { clientName })}<span className="accent">{window.tr(lang, 's04.title_h_accent')}</span>{window.tr(lang, 's04.title_tail')}
            </h2>
          </div>
          <p className="t-body" style={{ maxWidth: 420, textAlign: 'right', color: 'var(--ink-secondary)' }}>
            {window.tr(lang, 's04.subtitle')}
          </p>
        </div>

        <MonoKicker beam beamDelay={2}>{window.tr(lang, 's04.mono_obs')}</MonoKicker>

        <div className="stagger" style={{
          flex: 1, display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 24,
          '--stagger-base': '0.15s', '--stagger-step': '0.08s',
        }}>
          {/* Acquirers */}
          <div className="card-nova" style={{ padding: 36, display: 'flex', flexDirection: 'column' }}>
            <div className="t-label" style={{ color: 'var(--accent-deep)', marginBottom: 8 }}>{window.tr(lang, 's04.acquirers_label')}</div>
            <div style={{ fontSize: 13, color: 'var(--ink-muted)', marginBottom: 22, lineHeight: 1.5 }}>
              {window.tr(lang, 's04.acquirers_desc')}
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10, flex: 1 }}>
              {acquirers.map((a, i) => (
                <div key={i} style={{
                  padding: '14px 16px',
                  background: 'rgba(62,79,224,0.04)',
                  border: '1px solid rgba(62,79,224,0.10)',
                  borderRadius: 10,
                  fontSize: 15, fontWeight: 600, color: 'var(--ink-strong)',
                }}>{a}</div>
              ))}
            </div>
          </div>

          {/* Gateways */}
          <div className="card-nova" style={{ padding: 36, display: 'flex', flexDirection: 'column' }}>
            <div className="t-label" style={{ color: 'var(--accent-deep)', marginBottom: 8 }}>{window.tr(lang, 's04.gateways_label')}</div>
            <div style={{ fontSize: 13, color: 'var(--ink-muted)', marginBottom: 22, lineHeight: 1.5 }}>
              {window.tr(lang, 's04.gateways_desc')}
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10, flex: 1 }}>
              {gateways.map((g, i) => (
                <div key={i} style={{
                  padding: '14px 16px',
                  background: 'rgba(62,79,224,0.04)',
                  border: '1px solid rgba(62,79,224,0.10)',
                  borderRadius: 10,
                  fontSize: 15, fontWeight: 600, color: 'var(--ink-strong)',
                }}>{g}</div>
              ))}
            </div>
          </div>

          {/* Methods — dark card */}
          <div className="card-nova card-dark border-beam" style={{
            padding: 36, display: 'flex', flexDirection: 'column', position: 'relative',
          }}>
            <div className="t-label" style={{ color: 'var(--lime)', marginBottom: 8 }}>{window.tr(lang, 's04.methods_label')}</div>
            <div style={{ fontSize: 13, color: 'rgba(255,255,255,0.6)', marginBottom: 22, lineHeight: 1.5 }}>
              {window.tr(lang, 's04.methods_desc')}
            </div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
              {methods.map((m, i) => (
                <span key={i} style={{
                  padding: '8px 14px',
                  background: 'rgba(255,255,255,0.06)',
                  border: '1px solid rgba(255,255,255,0.12)',
                  borderRadius: 999,
                  fontSize: 13, color: '#fff', fontWeight: 500,
                }}>{m}</span>
              ))}
            </div>
          </div>
        </div>

        {/* Observations strip */}
        <div className="card-nova" style={{
          flexShrink: 0, padding: '22px 32px',
          display: 'grid', gridTemplateColumns: 'auto 1fr', gap: 28, alignItems: 'start',
        }}>
          <div className="t-label" style={{ color: 'var(--accent-deep)' }}>{window.tr(lang, 's04.observations_label')}</div>
          <div style={{ display: 'grid', gridTemplateColumns: `repeat(${Math.min(observations.length, 4)}, 1fr)`, gap: 24 }}>
            {observations.slice(0, 4).map((o, i) => (
              <div key={i} style={{ fontSize: 13, color: 'var(--ink-secondary)', lineHeight: 1.55 }}>
                <span style={{ color: 'var(--accent)', marginRight: 6, fontWeight: 700 }}>·</span>{o}
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

// =============================================================================
// Slide 05 — Geography (world map + share-by-country side panel)
// Pin coords come from SVG_COUNTRY_COORDS (Equal Earth, defined at the top of
// this file next to NAME_TO_ISO).
// =============================================================================
function Slide05Geography({ data }) {
  const lang = pickLang(data);
  const clientName = data.clientName || '{{client}}';
  const rawMarkets = data.markets_geo || [
    { name: 'United States',  share: 32 },
    { name: 'Mexico',         share: 14 },
    { name: 'Brazil',         share: 12 },
    { name: 'United Kingdom', share:  9 },
    { name: 'India',          share:  8 },
  ];
  const markets = rawMarkets.map((m) => {
    const name = m.name || m.country;
    const xy = (m.x != null && m.y != null) ? { x: m.x, y: m.y } : svgCoordsFor(name);
    return { name, share: Number(m.share) || 0, iso: isoFor(name), ...(xy || {}) };
  });
  const top = [...markets].sort((a, b) => b.share - a.share);
  const lead = top[0] || { share: 0, name: '—' };
  const totalShare = top.reduce((s, m) => s + m.share, 0);

  return (
    <div className="slide theme-light" data-screen-label="05 Geography">
      <SlideChrome section={window.tr(lang, 'common.context_geography')} pageNum={5} />

      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 24 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: 36 }}>
          <div>
            <MonoKicker beam={false} style={{ marginBottom: 14 }}>{window.tr(lang, 's05.mono_kicker')}</MonoKicker>
            <h2 className="t-title t-title-m" style={{ maxWidth: 1100 }}>
              {window.trf(lang, 's05.title_head', { clientName })}<span className="accent">{window.trf(lang, 's05.title_accent', { share: lead.share })}</span>{window.trf(lang, 's05.title_tail', { name: lead.name })}
            </h2>
          </div>
          <p className="t-body" style={{ maxWidth: 400, textAlign: 'right', color: 'var(--ink-secondary)' }}>
            {window.trf(lang, 's05.subtitle', { topLen: top.length, totalShare, clientName })}
          </p>
        </div>

        <MonoKicker beam beamDelay={2}>{window.tr(lang, 's05.mono_reach')}</MonoKicker>

        <div className="stagger" style={{
          flex: 1, display: 'grid', gridTemplateColumns: '1fr 440px', gap: 48, alignItems: 'center',
          minHeight: 0, '--stagger-base': '0.15s', '--stagger-step': '0.1s',
        }}>
          {/* World map (matches Phase-0 preview: pitch-maker SVG with Yuno-blue
              filter overlay + pulse-pins for the markets we can place). */}
          <div style={{
            position: 'relative', width: '100%', aspectRatio: '2 / 1',
          }}>
            <img
              src="/sdr-bc-assets/world-map.svg"
              alt=""
              style={{
                position: 'absolute', inset: 0,
                width: '100%', height: '100%',
                objectFit: 'contain',
                opacity: 0.18,
                filter: 'brightness(0) saturate(100%) invert(28%) sepia(98%) saturate(2900%) hue-rotate(229deg) brightness(95%) contrast(92%)',
              }}
            />
            {markets.filter(m => m.x != null && m.y != null).map((m, i) => {
              const size = 14 + Math.sqrt(m.share) * 2.5;
              return (
                <div key={m.name} style={{
                  position: 'absolute',
                  left: m.x + '%', top: m.y + '%',
                  width: 0, height: 0, zIndex: 3,
                }}>
                  <div style={{
                    position: 'absolute', top: 0, left: 0,
                    width: size, height: size,
                    transform: 'translate(-50%,-50%)', borderRadius: '50%',
                    background: 'var(--accent-mid)',
                    boxShadow: '0 0 0 4px rgba(89,103,228,0.20)',
                    zIndex: 2,
                  }} />
                  <div style={{
                    position: 'absolute', top: 0, left: 0,
                    width: size * 2.2, height: size * 2.2,
                    borderRadius: '50%',
                    border: '1.5px solid rgba(62,79,224,0.55)',
                    animation: 'pulseRing 2.6s ease-out infinite',
                    animationDelay: (i * 0.4) + 's',
                    transform: 'translate(-50%,-50%)', zIndex: 1,
                  }} />
                  <div style={{
                    position: 'absolute', top: -(size + 10) + 'px', left: 0,
                    transform: 'translateX(-50%)',
                    fontFamily: 'var(--font-mono)', fontSize: 12, fontWeight: 700,
                    color: 'var(--ink-strong)', whiteSpace: 'nowrap', letterSpacing: '0.05em',
                  }}>
                    {m.iso} · {m.share}%
                  </div>
                </div>
              );
            })}
          </div>

          {/* Side panel: share by country */}
          <div style={{
            display: 'flex', flexDirection: 'column', gap: 16,
            paddingLeft: 32, borderLeft: '1px solid var(--border-subtle)',
            alignSelf: 'stretch', justifyContent: 'center',
          }}>
            <div className="t-label" style={{ color: 'var(--accent-deep)', marginBottom: 6 }}>
              {window.tr(lang, 's05.share_by_country')}
            </div>
            {top.map(m => (
              <div key={m.name} style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
                  <span style={{ fontSize: 17, fontWeight: 600, color: 'var(--ink-strong)' }}>{m.name}</span>
                  <span className="t-number" style={{
                    fontSize: 22, fontWeight: 500, color: 'var(--accent)', letterSpacing: '-0.02em',
                  }}>
                    {m.share}%
                  </span>
                </div>
                <div style={{
                  width: '100%', height: 4,
                  background: 'rgba(30,32,48,0.06)', borderRadius: 2, overflow: 'hidden',
                }}>
                  <div style={{
                    width: m.share + '%', height: '100%',
                    background: 'linear-gradient(90deg, var(--accent-deep) 0%, var(--accent) 100%)',
                    borderRadius: 2,
                  }} />
                </div>
              </div>
            ))}
            <div style={{
              marginTop: 12, paddingTop: 16,
              borderTop: '1px solid var(--border-subtle)',
              fontFamily: 'var(--font-mono)', fontSize: 11,
              color: 'var(--ink-muted)', lineHeight: 1.6,
            }}>
              {window.tr(lang, 's05.source_footer_top')}<br/>
              {window.trf(lang, top.length === 1 ? 's05.source_footer_count_one' : 's05.source_footer_count_many', { n: top.length })}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// Continent dots — rendered inline. Generated from polygon-rasterized world map
// (same approach as the old slide-5 code, but at lower density for the card
// surface). Light-mode tint.
function ContinentDotsBg() {
  // Pre-computed sparse silhouette — kept compact for inline rendering.
  // Each entry is (x, y) % position. Generated once at module load.
  const dots = useMemo(() => {
    const polygons = [
      [3,11,8,8,13,8,16,10,22,9,28,10,30,14,30,21,28,24,31,25,31,30,29,34,26,38,24,38,23,42,24,45,26,46,23,46,21,42,19,38,17,34,14,28,13,22,11,17,8,15,5,14],
      [28,46,31,45,34,47,35,50,38,53,39,57,40,60,38,64,35,68,33,73,32,78,30,82,29,83,28,80,28,73,27,67,26,60,26,53,27,50],
      [43,19,46,19,46,24,44,25,42,24,42,21],
      [48,12,52,11,54,15,53,20,50,22,47,21,47,16],
      [44,22,46,21,50,22,54,23,56,24,55,28,52,29,49,29,46,28,44,26],
      [42,28,47,28,47,33,44,34,42,32],
      [49,28,51,28,52,32,51,34,50,33,49,30],
      [54,20,64,21,65,25,62,28,56,28,54,25],
      [55,10,63,9,72,8,82,9,90,10,95,11,95,15,93,18,90,20,84,21,78,22,72,22,66,22,60,22,56,21,55,17],
      [55,30,60,30,64,29,69,30,71,33,70,37,66,42,62,45,59,44,56,40,54,36,54,32],
      [68,36,73,36,75,40,73,46,72,50,70,52,68,50,67,45,66,40],
      [72,24,80,23,86,24,89,27,86,32,88,35,87,38,83,39,78,38,74,36,72,32,72,28],
      [88,28,90,28,90,30,88,30], [88,30,91,30,92,33,90,35,88,33], [89,34,91,34,91,37,89,37],
      [74,38,80,38,83,40,84,45,82,49,80,52,78,50,76,46,75,42],
      [80,55,84,55,86,59,84,60,81,58], [85,59,90,59,91,61,87,62,85,61],
      [80,64,92,64,94,67,93,72,91,75,86,75,82,73,80,69],
      [44,34,48,34,52,34,56,35,60,36,62,38,62,42,60,44,58,47,58,52,57,57,55,62,53,66,53,71,54,75,52,77,50,73,48,68,47,62,46,56,45,50,44,44,43,40,43,36],
    ];
    const inside = (px, py, poly) => {
      let isIn = false;
      for (let i = 0, j = poly.length - 2; i < poly.length; j = i, i += 2) {
        const xi = poly[i], yi = poly[i + 1];
        const xj = poly[j], yj = poly[j + 1];
        if (((yi > py) !== (yj > py)) && (px < ((xj - xi) * (py - yi)) / (yj - yi) + xi)) isIn = !isIn;
      }
      return isIn;
    };
    const out = [];
    const step = 1.4;
    for (let x = 0; x <= 100; x += step) {
      for (let y = 0; y <= 100; y += step) {
        for (const poly of polygons) {
          if (inside(x, y, poly)) { out.push({ x, y }); break; }
        }
      }
    }
    return out;
  }, []);

  return (
    <svg width="100%" height="100%" viewBox="0 0 100 100" preserveAspectRatio="none">
      {dots.map((d, i) => (
        <circle key={i} cx={d.x} cy={d.y} r={0.42} fill="rgba(62,79,224,0.32)" />
      ))}
    </svg>
  );
}

// =============================================================================
// Slide 06 — Orchestration "stack actual" — ported from workshop slide 14
// (src/workshops-bc/components/slides/SlideStack.jsx). Two side-by-side trees
// rendered with absolute positioning so the connectors line up cleanly:
//
//   LEFT (sin Yuno · hoy)               RIGHT (con Yuno · target)
//     [client tx ribbon]                  [client tx ribbon]
//           │                                    │
//     [antifraud · opt]               [yuno orchestration bar  · chips]
//           │                                    │
//     ───┬─────┬───                        [antifraud · cascade]
//        │     │                                 │
//   [PRIMARY] [SECONDARY]            ───┬───┬───┬───┬───┬───
//                                       │   │   │   │   │
//                                  [INT][INT][NEW][NEW][NEW]
//                                  (each card has ✓ / ⚠ / ✕ status rows)
//
// Data driven by orchestration_* tokens emitted by sdr-bc-generate.
// =============================================================================
function Slide06Orchestration({ data }) {
  const lang = pickLang(data);
  const clientName = data.clientName || '{{client}}';
  const txPerMonth = data.orchestration_client_tx_per_month || '~1M';
  const arPct = data.orchestration_client_ar_pct || 80;
  const currentPsps = Array.isArray(data.orchestration_current_psps) ? data.orchestration_current_psps : [];
  const currentAntifraud = data.orchestration_current_antifraud || null;
  const proposedAntifraudPrimary = data.orchestration_proposed_antifraud || 'Cybersource';
  const proposedAntifraudCascade = data.orchestration_proposed_antifraud_cascade || 'Riskified';
  const proposedPspsAll = Array.isArray(data.orchestration_proposed_psps) ? data.orchestration_proposed_psps : [];
  const proposedPsps = proposedPspsAll.slice(0, 5);

  // Old slugs (generated before orchestration_* tokens existed) have no PSP data.
  // We still render the diagram, but flag it so the reader knows it's a stale deck.
  const isStale = currentPsps.length === 0 && proposedPsps.length === 0;

  // ── Geometry — ported VERBATIM from workshop SlideStack.jsx ──
  const NODE_H = 76;
  const LEFT_CX = 430;
  const RIGHT_CX = 1330;
  const AF_W = 180;
  const CYB_CX = RIGHT_CX - 100;
  const RSK_CX = RIGHT_CX + 100;
  const RIGHT_ACQ_W = 152;
  const RIGHT_ACQ_STEP = 170;
  const RIGHT_ACQ_CENTERS = [-2, -1, 0, 1, 2].map(i => RIGHT_CX + i * RIGHT_ACQ_STEP);
  const LEFT_NODE_W = 240;
  const LEFT_ACQ_W = 200;
  const LEFT_ACQ_CENTERS = [LEFT_CX - 130, LEFT_CX + 130];
  const RIGHT_NODE_W = 240;
  const YUNO_BAR_X = 920;
  const YUNO_BAR_W = 820;
  const Y_PILL = 0;
  const Y_COPPEL = 40;
  const Y_COPPEL_B = Y_COPPEL + NODE_H;          // 116
  const Y_YUNO = 180;
  const Y_YUNO_B = Y_YUNO + NODE_H;              // 256
  const Y_AF = 320;
  const Y_AF_B = Y_AF + NODE_H;                  // 396
  const Y_JUNCTION = 425;
  const Y_SPLIT_BAR = 445;
  const Y_ACQ = 460;
  const ACQ_H_LEFT = 96;
  const ACQ_H_RIGHT = 140;

  // ── Inline node primitives (workshop has them as separate components — we
  // inline here since the SDR BC bundle is babel-in-browser, no ES modules). ──
  function inlineNode({ x, y, w, h = NODE_H, name, sub, variant = 'default', breathe = false, key }) {
    const muted = variant === 'muted';
    return (
      <div key={key} style={{
        position: 'absolute', left: x, top: y, width: w, height: h,
        background: '#fff',
        border: `1px solid ${muted ? 'rgba(40,42,48,0.10)' : 'var(--border-default)'}`,
        borderRadius: 12,
        boxShadow: muted ? 'none' : '0 4px 14px rgba(40,42,48,0.06)',
        display: 'flex', flexDirection: 'column',
        justifyContent: 'center', alignItems: 'center',
        padding: '0 18px',
        animation: breathe ? 'nodeBreathe 2.6s ease-in-out infinite' : undefined,
      }}>
        <div style={{
          fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 20,
          color: 'var(--ink-strong)', letterSpacing: '-0.02em', lineHeight: 1.1,
          textAlign: 'center',
        }}>{name}</div>
        {sub && (
          <div style={{
            fontFamily: 'var(--font-mono)', fontSize: 11,
            color: 'var(--ink-muted)', marginTop: 4, letterSpacing: '0.02em',
          }}>{sub}</div>
        )}
      </div>
    );
  }

  function inlineYunoBar() {
    return (
      <div style={{
        position: 'absolute', left: YUNO_BAR_X, top: Y_YUNO,
        width: YUNO_BAR_W, height: NODE_H,
        background: 'linear-gradient(135deg, var(--accent) 0%, var(--accent-deep) 100%)',
        border: '1px solid var(--accent-deep)',
        borderRadius: 12,
        display: 'flex', alignItems: 'center', gap: 18,
        padding: '0 22px',
        animation: 'yunoBarBreathe 3.2s ease-in-out infinite',
      }}>
        <span style={{
          fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 22,
          color: '#fff', letterSpacing: '-0.02em',
        }}>yuno</span>
        <span style={{
          fontFamily: 'var(--font-mono)', fontSize: 14,
          color: 'rgba(255,255,255,0.85)', letterSpacing: '0.02em',
        }}>{window.tr(lang, 'sOrch.yuno_orchestration_label')}</span>
        <div style={{ flex: 1, display: 'flex', gap: 6, flexWrap: 'wrap', justifyContent: 'flex-end' }}>
          {['Smart Routing', 'Vault', 'Reconciliation', 'Fraud', 'Payouts'].map(cap => (
            <span key={cap} style={{
              padding: '4px 10px', borderRadius: 999,
              background: 'rgba(255,255,255,0.12)',
              border: '1px solid rgba(255,255,255,0.20)',
              fontSize: 10, fontWeight: 600,
              color: '#fff', letterSpacing: '0.04em',
              whiteSpace: 'nowrap',
            }}>{cap}</span>
          ))}
        </div>
      </div>
    );
  }

  function inlinePlainAcquirerCard({ x, y, w, role, name, key }) {
    return (
      <div key={key} style={{
        position: 'absolute', left: x, top: y, width: w, height: ACQ_H_LEFT,
        background: '#fff',
        border: '1px solid rgba(40,42,48,0.10)',
        borderRadius: 10,
        display: 'flex', flexDirection: 'column',
        justifyContent: 'center', alignItems: 'center',
        padding: '0 10px',
        boxShadow: '0 4px 14px rgba(40,42,48,0.06)',
      }}>
        {role && (
          <div style={{
            fontSize: 9, color: 'var(--ink-muted)',
            letterSpacing: '0.16em', marginBottom: 6, textTransform: 'uppercase', fontWeight: 700,
          }}>{role}</div>
        )}
        <div style={{
          fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 17,
          color: 'var(--ink-strong)', letterSpacing: '-0.02em', lineHeight: 1, textAlign: 'center',
        }}>{name}</div>
      </div>
    );
  }

  function inlineStatusRow({ icon, label, color, active = false, delay = '0s' }) {
    return (
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        gap: 6, fontSize: 9, color: 'var(--ink-muted)',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
          <span style={{
            width: 11, height: 11, borderRadius: '50%',
            background: '#fff',
            border: `1px solid ${color}`,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            color, fontSize: 7, fontWeight: 700, flexShrink: 0,
          }}>{icon}</span>
          <span>{label}</span>
        </div>
        {active ? (
          <span style={{
            width: 14, height: 14, borderRadius: 3,
            background: 'rgba(62,79,224,0.14)',
            border: '1px solid rgba(62,79,224,0.45)',
            color: 'var(--accent)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: 11, fontWeight: 800, lineHeight: 1,
            animation: 'cascadeCaretPulseBlue 2.2s ease-in-out infinite',
            animationDelay: delay,
          }}>›</span>
        ) : (
          <span style={{
            width: 10, height: 10, borderRadius: 3,
            background: 'rgba(40,42,48,0.04)', border: '1px solid rgba(40,42,48,0.10)',
          }} />
        )}
      </div>
    );
  }

  function inlinePspAcquirerCard({ x, y, w, role, name, cascadeDelay = '0s', key }) {
    return (
      <div key={key} style={{
        position: 'absolute', left: x, top: y, width: w, height: ACQ_H_RIGHT,
        background: '#fff',
        border: '1px solid rgba(40,42,48,0.10)',
        borderRadius: 10,
        padding: '12px 12px',
        boxShadow: '0 6px 18px rgba(62,79,224,0.10)',
        display: 'flex', flexDirection: 'column', gap: 8,
      }}>
        <div style={{
          fontSize: 8, color: 'var(--accent-deep)',
          letterSpacing: '0.16em', textAlign: 'center', textTransform: 'uppercase', fontWeight: 700,
        }}>{role}</div>
        <div style={{
          fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 16,
          color: 'var(--ink-strong)',
          letterSpacing: '-0.02em', lineHeight: 1, textAlign: 'center',
        }}>{name}</div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 4, marginTop: 4 }}>
          {inlineStatusRow({ icon: '✓', label: window.tr(lang, 'sOrch.status_approve'),  color: '#16A34A',           active: false })}
          {inlineStatusRow({ icon: '⚠', label: window.tr(lang, 'sOrch.status_fallback'), color: 'var(--accent)',     active: true, delay: cascadeDelay })}
          {inlineStatusRow({ icon: '✕', label: window.tr(lang, 'sOrch.status_error'),    color: 'rgba(40,42,48,0.30)', active: false })}
        </div>
      </div>
    );
  }

  function inlineHeaderPill({ x, y, w, label, accent }) {
    return (
      <div style={{
        position: 'absolute', left: x, top: y, width: w,
        display: 'flex', justifyContent: 'center',
      }}>
        <span style={{
          display: 'inline-flex', alignItems: 'center', gap: 8,
          padding: '6px 14px', borderRadius: 999,
          background: `${accent}14`,
          border: `1px solid ${accent}55`,
          color: accent, fontSize: 10, fontWeight: 700,
          letterSpacing: '0.18em', textTransform: 'uppercase',
        }}>
          <span style={{ width: 5, height: 5, borderRadius: '50%', background: accent }} />
          {label}
        </span>
      </div>
    );
  }

  // ── SVG TreeWires — ALL wires + animations ported from workshop ──
  function TreeWires() {
    const muted = 'rgba(40,42,48,0.22)';
    const stroke = 'rgba(62,79,224,0.55)';
    const beam = '#7C89EF';

    // Canonical happy-path for the payment packet animation:
    // Client → Yuno → AF split → Cybersource → junction → split bar → first acquirer
    const packetPath = [
      `M ${RIGHT_CX},${Y_COPPEL_B}`,
      `V ${Y_YUNO}`,
      `V ${Y_YUNO_B}`,
      `V 290`,
      `H ${CYB_CX}`,
      `V ${Y_AF}`,
      `V ${Y_AF_B}`,
      `V ${Y_JUNCTION - 10}`,
      `H ${RIGHT_CX}`,
      `V ${Y_JUNCTION}`,
      `V ${Y_SPLIT_BAR}`,
      `H ${RIGHT_ACQ_CENTERS[0]}`,
      `V ${Y_ACQ}`,
    ].join(' ');

    // Only render right-side wires for slots that have acquirer cards;
    // otherwise the wires hang into empty space and look broken.
    const numAcqs = Math.max(proposedPsps.length, 0);
    const acqXs = numAcqs > 0 ? RIGHT_ACQ_CENTERS.slice(0, numAcqs) : [];

    const rightWires = [
      { d: `M ${RIGHT_CX},${Y_COPPEL_B} V ${Y_YUNO}`, dur: 2.4, delay: 0 },
      { d: `M ${RIGHT_CX},${Y_YUNO_B} V 290`, dur: 1.4, delay: -0.3 },
      { d: `M ${CYB_CX},290 H ${RSK_CX}`, dur: 2.2, delay: -0.5 },
      { d: `M ${CYB_CX},290 V ${Y_AF}`, dur: 1.4, delay: -0.7 },
      { d: `M ${RSK_CX},290 V ${Y_AF}`, dur: 1.4, delay: -0.9 },
      { d: `M ${CYB_CX},${Y_AF_B} V ${Y_JUNCTION - 10} H ${RIGHT_CX} V ${Y_JUNCTION}`, dur: 2.4, delay: -1.1 },
      { d: `M ${RSK_CX},${Y_AF_B} V ${Y_JUNCTION - 10} H ${RIGHT_CX} V ${Y_JUNCTION}`, dur: 2.4, delay: -1.4 },
    ];
    if (numAcqs > 0) {
      rightWires.push({ d: `M ${RIGHT_CX},${Y_JUNCTION} V ${Y_SPLIT_BAR}`, dur: 1.2, delay: -1.6 });
      if (numAcqs > 1) {
        rightWires.push({
          d: `M ${acqXs[0]},${Y_SPLIT_BAR} H ${acqXs[acqXs.length - 1]}`,
          dur: 2.8, delay: -1.8,
        });
      }
      acqXs.forEach((cx, i) => {
        rightWires.push({
          d: `M ${cx},${Y_SPLIT_BAR} V ${Y_ACQ}`,
          dur: 1.0, delay: -2.0 - i * 0.08,
        });
      });
    }

    return (
      <svg
        width="1760" height="640" viewBox="0 0 1760 640"
        style={{ position: 'absolute', left: 0, top: 0, pointerEvents: 'none', overflow: 'visible' }}
      >
        <defs>
          <filter id="stackBeamGlow" x="-50%" y="-50%" width="200%" height="200%">
            <feGaussianBlur stdDeviation="1" result="b" />
            <feMerge>
              <feMergeNode in="b" /><feMergeNode in="SourceGraphic" />
            </feMerge>
          </filter>
          <radialGradient id="packetGlow" cx="50%" cy="50%" r="50%">
            <stop offset="0%" stopColor="rgba(189,195,246,0.95)" />
            <stop offset="100%" stopColor="rgba(189,195,246,0)" />
          </radialGradient>
        </defs>

        {/* ── LEFT TREE (sin Yuno) — muted, single slow beam to hint life ── */}
        {currentAntifraud ? (
          <>
            <line x1={LEFT_CX} y1={Y_COPPEL_B} x2={LEFT_CX} y2={Y_AF} stroke={muted} strokeWidth="1.5" />
            <line x1={LEFT_CX} y1={Y_AF_B}     x2={LEFT_CX} y2={Y_SPLIT_BAR} stroke={muted} strokeWidth="1.5" />
          </>
        ) : (
          <line x1={LEFT_CX} y1={Y_COPPEL_B} x2={LEFT_CX} y2={Y_SPLIT_BAR} stroke={muted} strokeWidth="1.5" />
        )}
        {currentPsps.length > 0 && (
          <>
            <line
              x1={LEFT_ACQ_CENTERS[0]} y1={Y_SPLIT_BAR}
              x2={LEFT_ACQ_CENTERS[Math.min(currentPsps.length - 1, 1)]} y2={Y_SPLIT_BAR}
              stroke={muted} strokeWidth="1.5"
            />
            {currentPsps.map((_, i) => (
              <line
                key={`L-${i}`}
                x1={LEFT_ACQ_CENTERS[i]} y1={Y_SPLIT_BAR}
                x2={LEFT_ACQ_CENTERS[i]} y2={Y_ACQ}
                stroke={muted} strokeWidth="1.5"
              />
            ))}
            <circle cx={LEFT_CX} cy={Y_SPLIT_BAR} r="2.5" fill={muted} />
          </>
        )}
        {/* Left slow static beam */}
        <line
          x1={LEFT_CX} y1={Y_COPPEL_B} x2={LEFT_CX} y2={currentAntifraud ? Y_AF : Y_SPLIT_BAR}
          stroke={muted} strokeWidth="2" strokeLinecap="round"
          pathLength="100" strokeDasharray="14 86" opacity="0.7"
        >
          <animate attributeName="stroke-dashoffset" from="0" to="-100" dur="6s" repeatCount="indefinite" />
        </line>

        {/* ── RIGHT TREE (con Yuno) — animated beams ── */}
        {rightWires.map((w, i) => (
          <g key={`R-${i}`}>
            <path d={w.d} fill="none" stroke={stroke} strokeWidth="1.5" />
            <path d={w.d} fill="none" stroke={beam} strokeWidth="2.5"
              strokeLinecap="round" pathLength="100" strokeDasharray="22 78"
              filter="url(#stackBeamGlow)">
              <animate attributeName="stroke-dashoffset"
                from="0" to="-100"
                dur={`${w.dur}s`} begin={`${w.delay}s`}
                repeatCount="indefinite" />
            </path>
          </g>
        ))}

        {/* Junction dot — pulses at the center where AFs converge */}
        {numAcqs > 0 && (
          <circle cx={RIGHT_CX} cy={Y_JUNCTION} r="5"
            fill="var(--accent)" filter="url(#stackBeamGlow)">
            <animate attributeName="r" values="4;6;4" dur="2.4s" repeatCount="indefinite" />
            <animate attributeName="opacity" values="0.6;1;0.6" dur="2.4s" repeatCount="indefinite" />
          </circle>
        )}

        {/* Payment packet — travels happy path on a 7s loop (only when full path exists) */}
        {numAcqs > 0 && (
          <>
            <circle r="9" fill="url(#packetGlow)">
              <animateMotion dur="7s" repeatCount="indefinite" path={packetPath} />
            </circle>
            <circle r="4" fill="#fff" stroke="var(--accent)" strokeWidth="2">
              <animateMotion dur="7s" repeatCount="indefinite" path={packetPath} />
            </circle>
          </>
        )}
      </svg>
    );
  }

  // ── Padded current PSPs so the left tree always has 2 slots (visually) ──
  // If research found 0 or 1, render the missing slot as an italic "—" so the
  // diagram still reads as "primary + secondary" instead of just one card.
  const leftSlots = [
    currentPsps[0] || null,
    currentPsps[1] || null,
  ];

  return (
    <div className="slide theme-light" data-screen-label="06 Stack actual">
      {/* Scoped keyframes — same ones the workshop uses */}
      <style>{`
        @keyframes cascadeCaretPulseBlue {
          0%, 100% { opacity: 0.75; box-shadow: 0 0 0 rgba(62,79,224,0); }
          50%      { opacity: 1;    box-shadow: 0 0 8px rgba(62,79,224,0.55); }
        }
        @keyframes nodeBreathe {
          0%, 100% { box-shadow: 0 4px 14px rgba(40,42,48,0.06), 0 0 0 0 rgba(62,79,224,0); }
          50%      { box-shadow: 0 6px 22px rgba(62,79,224,0.16), 0 0 0 4px rgba(62,79,224,0.06); }
        }
        @keyframes yunoBarBreathe {
          0%, 100% { box-shadow: 0 10px 30px rgba(62,79,224,0.30); }
          50%      { box-shadow: 0 14px 40px rgba(62,79,224,0.42), 0 0 0 6px rgba(62,79,224,0.08); }
        }
      `}</style>

      <SlideChrome section={window.tr(lang, 'common.context_stack_actual')} pageNum={6} />

      {/* Title block */}
      <div style={{ position: 'relative', zIndex: 2 }}>
        <MonoKicker beam={false} style={{ marginBottom: 12 }}>{window.tr(lang, 'sOrch.mono_kicker')}</MonoKicker>
        <h2 className="t-title t-title-m" style={{ maxWidth: 1500 }}>
          {window.trf(lang, 'sOrch.title_head', { clientName })}{' '}
          <span className="accent">{window.tr(lang, 'sOrch.title_accent')}</span>{window.tr(lang, 'sOrch.title_tail')}
        </h2>
      </div>

      {/* Stale data banner — only shown for decks generated before orchestration tokens */}
      {isStale && (
        <div style={{
          marginTop: 14,
          padding: '8px 14px',
          fontSize: 12,
          background: 'rgba(245,158,11,0.08)',
          border: '1px solid rgba(245,158,11,0.32)',
          borderRadius: 8,
          color: '#92400E',
          display: 'inline-block',
          letterSpacing: '0.02em',
        }}>
          {window.tr(lang, 'sOrch.stale_warning') || 'Stack data unavailable — this deck was generated before this slide existed. Re-run to populate.'}
        </div>
      )}

      {/* Tree area — 1760×640 absolute coordinate space */}
      <div style={{
        position: 'relative',
        width: 1760, height: 640,
        marginTop: 20,
      }}>
        {/* Vertical divider between left and right trees */}
        <div aria-hidden style={{
          position: 'absolute', left: 880, top: 36, bottom: 24, width: 1,
          background: 'linear-gradient(180deg, rgba(40,42,48,0) 0%, rgba(40,42,48,0.10) 18%, rgba(40,42,48,0.10) 82%, rgba(40,42,48,0) 100%)',
        }} />

        {/* SVG wire layer (below cards) */}
        <TreeWires />

        {/* ── LEFT TREE — sin Yuno · hoy ── */}
        {inlineHeaderPill({ x: 0, y: Y_PILL, w: 880, label: window.tr(lang, 'sOrch.left_header'), accent: 'rgba(40,42,48,0.55)' })}

        {inlineNode({
          x: LEFT_CX - LEFT_NODE_W / 2, y: Y_COPPEL, w: LEFT_NODE_W,
          name: clientName,
          sub: `${txPerMonth} tx/mes · ${arPct}% AR (est.)`,
          variant: 'muted',
        })}

        {currentAntifraud && inlineNode({
          x: LEFT_CX - AF_W / 2, y: Y_AF, w: AF_W,
          name: currentAntifraud,
          sub: window.tr(lang, 'sOrch.role_antifraud'),
          variant: 'muted',
        })}

        {leftSlots.map((name, i) => (
          name ? inlinePlainAcquirerCard({
            key: `l-acq-${i}`,
            x: LEFT_ACQ_CENTERS[i] - LEFT_ACQ_W / 2, y: Y_ACQ, w: LEFT_ACQ_W,
            role: i === 0 ? window.tr(lang, 'sOrch.role_primary') : window.tr(lang, 'sOrch.role_secondary'),
            name,
          }) : (
            <div key={`l-acq-empty-${i}`} style={{
              position: 'absolute',
              left: LEFT_ACQ_CENTERS[i] - LEFT_ACQ_W / 2, top: Y_ACQ,
              width: LEFT_ACQ_W, height: ACQ_H_LEFT,
              background: 'rgba(40,42,48,0.02)',
              border: '1px dashed rgba(40,42,48,0.18)',
              borderRadius: 10,
              display: 'flex', flexDirection: 'column',
              justifyContent: 'center', alignItems: 'center',
              padding: '0 10px',
            }}>
              <div style={{
                fontSize: 9, color: 'var(--ink-muted)',
                letterSpacing: '0.16em', marginBottom: 6, textTransform: 'uppercase', fontWeight: 700,
              }}>{i === 0 ? window.tr(lang, 'sOrch.role_primary') : window.tr(lang, 'sOrch.role_secondary')}</div>
              <div style={{ fontSize: 15, color: 'var(--ink-muted)', fontStyle: 'italic' }}>—</div>
            </div>
          )
        ))}

        {/* ── RIGHT TREE — con Yuno · target ── */}
        {inlineHeaderPill({ x: 880, y: Y_PILL, w: 880, label: window.tr(lang, 'sOrch.right_header'), accent: 'var(--accent)' })}

        {inlineNode({
          x: RIGHT_CX - RIGHT_NODE_W / 2, y: Y_COPPEL, w: RIGHT_NODE_W,
          name: clientName,
          sub: `${txPerMonth} tx/mes`,
          breathe: true,
        })}

        {inlineYunoBar()}

        {inlineNode({
          x: CYB_CX - AF_W / 2, y: Y_AF, w: AF_W,
          name: proposedAntifraudPrimary,
          sub: window.tr(lang, 'sOrch.role_af_first_pass'),
          breathe: true,
        })}
        {inlineNode({
          x: RSK_CX - AF_W / 2, y: Y_AF, w: AF_W,
          name: proposedAntifraudCascade,
          sub: window.tr(lang, 'sOrch.role_af_cascade'),
          breathe: true,
        })}

        {proposedPsps.length > 0 ? (
          proposedPsps.map((psp, i) => inlinePspAcquirerCard({
            key: `r-acq-${i}`,
            x: RIGHT_ACQ_CENTERS[i] - RIGHT_ACQ_W / 2, y: Y_ACQ, w: RIGHT_ACQ_W,
            role: psp.role === 'nuevo' ? window.tr(lang, 'sOrch.role_new') : window.tr(lang, 'sOrch.role_integrated'),
            name: psp.name,
            cascadeDelay: `${i * 0.3}s`,
          }))
        ) : (
          // Empty right state: 5 dashed placeholders so the visual structure is preserved
          [0, 1, 2, 3, 4].map(i => (
            <div key={`r-acq-empty-${i}`} style={{
              position: 'absolute',
              left: RIGHT_ACQ_CENTERS[i] - RIGHT_ACQ_W / 2, top: Y_ACQ,
              width: RIGHT_ACQ_W, height: ACQ_H_RIGHT,
              background: 'rgba(62,79,224,0.02)',
              border: '1px dashed rgba(62,79,224,0.32)',
              borderRadius: 10,
              display: 'flex', flexDirection: 'column',
              justifyContent: 'center', alignItems: 'center',
              padding: '0 8px',
            }}>
              <div style={{
                fontSize: 8, color: 'var(--accent-deep)',
                letterSpacing: '0.16em', marginBottom: 6, textTransform: 'uppercase', fontWeight: 700,
              }}>{i < 2 ? window.tr(lang, 'sOrch.role_integrated') : window.tr(lang, 'sOrch.role_new')}</div>
              <div style={{ fontSize: 14, color: 'var(--ink-muted)', fontStyle: 'italic' }}>—</div>
            </div>
          ))
        )}
      </div>

      {/* Bottom comparison strip (matches workshop) */}
      <div style={{
        marginTop: 20,
        display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24,
      }}>
        <div style={{
          padding: '14px 20px', borderRadius: 10,
          background: 'rgba(40,42,48,0.04)',
          border: '1px solid rgba(40,42,48,0.10)',
          display: 'flex', alignItems: 'center', gap: 14,
        }}>
          <span className="t-label" style={{ color: 'var(--ink-muted)', fontSize: 10 }}>
            {window.tr(lang, 'sOrch.left_header').split(' · ')[1] || 'HOY'}
          </span>
          <span style={{ fontSize: 13, color: 'var(--ink-muted)', lineHeight: 1.4 }}>
            {window.trf(lang, 'sOrch.left_footnote', { n: currentPsps.length || 0 })}
          </span>
        </div>
        <div style={{
          padding: '14px 20px', borderRadius: 10,
          background: 'rgba(62,79,224,0.06)',
          border: '1px solid rgba(62,79,224,0.30)',
          display: 'flex', alignItems: 'center', gap: 14,
        }}>
          <span className="t-label" style={{ color: 'var(--accent-deep)', fontSize: 10 }}>
            {window.tr(lang, 'sOrch.right_header').split(' · ')[1] || 'TARGET'}
          </span>
          <span style={{ fontSize: 13, color: 'var(--ink-strong)', lineHeight: 1.4 }}>
            {window.trf(lang, 'sOrch.right_footnote', { n: proposedPsps.length || 0 })}
          </span>
        </div>
      </div>
    </div>
  );
}

// =============================================================================
// Slide 07 — Section · Why Yuno (was 06 before the orchestration slide insert)
// =============================================================================
function Slide06WhyYunoSection({ data }) {
  const lang = pickLang(data);
  return (
    <SectionDivider
      index="02"
      title={window.tr(lang, 's06.title')}
      subtitle={window.tr(lang, 's06.subtitle')}
      pageNum={7}
      lang={lang}
    />
  );
}

// =============================================================================
// Slide 07 — Yuno Overview
// =============================================================================
function Slide07YunoOverview({ data }) {
  const lang = pickLang(data);
  const stats = [
    { n: 1500, suf: '+', label: window.tr(lang, 's07.stats.payment_methods') },
    { n: 460,  suf: '+', label: window.tr(lang, 's07.stats.integrations') },
    { n: 180,  suf: '+', label: window.tr(lang, 's07.stats.countries') },
    { n: 200,  suf: '+', label: window.tr(lang, 's07.stats.currencies') },
  ];
  const suite = [
    {
      label: window.tr(lang, 's07.suite.orchestration.label'),
      items: [
        window.tr(lang, 's07.suite.orchestration.items.smart_routing'),
        window.tr(lang, 's07.suite.orchestration.items.multi_psp'),
        window.tr(lang, 's07.suite.orchestration.items.monitors'),
      ],
    },
    {
      label: window.tr(lang, 's07.suite.checkout.label'),
      items: [
        window.tr(lang, 's07.suite.checkout.items.modular_checkout'),
        window.tr(lang, 's07.suite.checkout.items.subs_engine'),
        window.tr(lang, 's07.suite.checkout.items.one_click'),
      ],
    },
    {
      label: window.tr(lang, 's07.suite.security.label'),
      items: [
        window.tr(lang, 's07.suite.security.items.network_tokens'),
        window.tr(lang, 's07.suite.security.items.tds'),
        window.tr(lang, 's07.suite.security.items.risk_conditions'),
      ],
    },
    {
      label: window.tr(lang, 's07.suite.insights.label'),
      items: [
        window.tr(lang, 's07.suite.insights.items.analytics'),
        window.tr(lang, 's07.suite.insights.items.reconciliation'),
        window.tr(lang, 's07.suite.insights.items.payouts'),
      ],
    },
  ];

  return (
    <div className="slide theme-light" data-screen-label="07 Yuno Overview">
      <SlideChrome section={window.tr(lang, 'common.why_yuno_platform')} pageNum={8} />

      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 28 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: 36 }}>
          <h2 className="t-title t-title-l" style={{ maxWidth: '66%' }}>
            {window.tr(lang, 's07.title_head')}<span className="accent">{window.tr(lang, 's07.title_accent')}</span>{window.tr(lang, 's07.title_tail')}
          </h2>
          <p className="t-body" style={{ maxWidth: '30%', textAlign: 'right', color: 'var(--ink-secondary)' }}>
            {window.tr(lang, 's07.subtitle')}
          </p>
        </div>

        <MonoKicker beam beamDelay={1.5}>platform_overview</MonoKicker>

        {/* Stats row */}
        <div className="stagger" style={{
          display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)',
          gap: 18, '--stagger-base': '0.15s', '--stagger-step': '0.06s',
        }}>
          {stats.map((s, i) => (
            <div key={i} className="card-nova" style={{ padding: 30 }}>
              <div className="t-number" style={{
                fontSize: 80, fontWeight: 300, color: 'var(--accent)',
                lineHeight: 0.95, letterSpacing: '-0.04em',
              }}>
                <Counter value={s.n} format={v => Math.round(v).toLocaleString()} delay={i * 100} />
                <span style={{ color: 'var(--accent-pale)' }}>{s.suf}</span>
              </div>
              <div className="t-label" style={{ marginTop: 16, color: 'var(--ink-muted)' }}>
                {s.label}
              </div>
            </div>
          ))}
        </div>

        {/* Suite columns */}
        <div className="stagger" style={{
          flex: 1, display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 18,
          '--stagger-base': '0.4s', '--stagger-step': '0.08s', minHeight: 0,
        }}>
          {suite.map((col, ci) => (
            <div key={ci} className="card-nova" style={{ padding: 28, display: 'flex', flexDirection: 'column' }}>
              <div className="t-label" style={{ color: 'var(--accent-deep)', marginBottom: 16 }}>
                {col.label}
              </div>
              <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 10 }}>
                {col.items.map((it, i) => (
                  <li key={i} style={{ fontSize: 14, color: 'var(--ink-secondary)', lineHeight: 1.5, display: 'flex', gap: 8 }}>
                    <span style={{ color: 'var(--accent)', fontWeight: 700 }}>·</span>
                    <span>{it}</span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// =============================================================================
// Slide 08 — Trusted By (logo set mirrors the SS deck SlideTrustedBy)
// =============================================================================

// Tile w/ styled text fallback. `text: true` skips the image entirely;
// otherwise the image loads from c.src and falls back to text on error.
function TrustedMerchantTile({ c }) {
  const [failed, setFailed] = React.useState(c.text === true);
  return (
    <div className="card-nova" style={{
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      padding: 14, minHeight: 0, overflow: 'hidden',
    }}>
      {failed || !c.src ? (
        <span style={{
          fontFamily: 'var(--font-display)', fontSize: 30,
          color: 'var(--ink)', lineHeight: 1,
          ...(c.style || {}),
        }}>{c.name}</span>
      ) : (
        <img
          src={c.src}
          alt={c.name}
          onError={() => setFailed(true)}
          style={{
            maxWidth: '68%', maxHeight: '50%',
            objectFit: 'contain',
            filter: 'brightness(0)',
            opacity: 0.88,
          }}
        />
      )}
    </div>
  );
}

// Image-with-text-fallback for the investor strip. Mirrors LogoOrText from
// SlideTrustedBy in the SS deck so both decks render the same row when the
// PNGs load and the same wordmarks when one 404s.
function InvestorMark({ inv }) {
  const [failed, setFailed] = React.useState(false);
  if (failed || !inv.src) {
    return (
      <span style={{
        fontSize: 14, fontWeight: 700, letterSpacing: '0.06em',
        textTransform: 'uppercase', color: 'var(--ink-secondary)',
        fontFamily: 'var(--font-display)', whiteSpace: 'nowrap',
      }}>{inv.name}</span>
    );
  }
  return (
    <img
      src={inv.src}
      alt={inv.name}
      onError={() => setFailed(true)}
      style={{
        height: 26, maxWidth: 140, objectFit: 'contain',
        filter: 'brightness(0)', opacity: 0.75,
        ...(inv.imgStyle || {}),
      }}
    />
  );
}

function Slide08Trust({ data }) {
  const lang = pickLang(data);
  // Logo set mirrors the SS deck (`/m/<slug>` → SlideTrustedBy) so the SDR BC
  // tells the same Trust story Yuno's main pitch uses. Assets are loaded
  // directly from /ss-deck-assets/trusted/* — single source of truth, no
  // duplication. Tile falls back to a styled text wordmark on 404.
  // 5 × 3 grid mirrors the deck.yuno.tools "Trusted by leading companies"
  // slide: 5 global super-apps/airlines/exchanges on top, 5 verified LATAM +
  // global proof points in the middle, 5 enterprise-tier customers on bottom.
  // Kraken has no local asset → SimpleIcons CDN serves a monochrome wordmark
  // (mirrors how Uber/McDonald's were sourced in the original Slide08).
  const SI = '0F1020';
  const clients = [
    // Row 1
    { name: 'Whop',          src: '/ss-deck-assets/trusted/whop.png',          style: { fontWeight: 700, letterSpacing: '4px', textTransform: 'uppercase', fontSize: 26 } },
    { name: "McDonald's",    src: '/ss-deck-assets/trusted/mcdonalds.png',     style: { fontWeight: 800, letterSpacing: '-0.5px' } },
    { name: 'Uber',          src: '/ss-deck-assets/trusted/uber.png',          style: { fontWeight: 800, letterSpacing: '-0.4px' } },
    { name: 'Crypto.com',    src: '/sdr-bc-assets/logos/cryptocom.svg',        style: { fontWeight: 700, letterSpacing: '-0.4px', fontSize: 26 } },
    { name: 'Samsung',       src: '/ss-deck-assets/trusted/samsung.png',       style: { fontWeight: 800, letterSpacing: '-0.3px' } },
    // Row 2
    { name: 'inDrive',       src: '/ss-deck-assets/trusted/indrive.svg',       style: { fontWeight: 700, letterSpacing: '-0.3px', fontSize: 28 } },
    { name: 'Ant Group',     src: '/ss-deck-assets/trusted/ant-group.png',     style: { fontWeight: 700, letterSpacing: '-0.2px' } },
    { name: 'Rappi',         src: '/ss-deck-assets/trusted/rappi.png',         style: { fontWeight: 800, letterSpacing: '-0.4px', fontStyle: 'italic' } },
    { name: 'GoFundMe',      src: '/ss-deck-assets/trusted/gofundme.png',      style: { fontWeight: 700, letterSpacing: '-0.3px', fontSize: 26 } },
    { name: 'NetEase Games', src: '/ss-deck-assets/trusted/netease-games.png', style: { fontWeight: 700, letterSpacing: '-0.2px', fontSize: 24 } },
    // Row 3
    { name: 'SpaceX',        src: '/sdr-bc-assets/logos/spacex.svg',           style: { fontWeight: 600, letterSpacing: '4px', textTransform: 'uppercase', fontSize: 24 } },
    { name: 'Zuora',         src: '/sdr-bc-assets/logos/zuora.svg',            style: { fontWeight: 700, letterSpacing: '-0.2px', fontSize: 28 } },
    { name: 'MoonActive',    src: '/sdr-bc-assets/logos/moonactive.png',       style: { fontWeight: 700, letterSpacing: '0.04em', textTransform: 'uppercase', fontSize: 22 } },
    { name: 'Qatar Airways', src: `https://cdn.simpleicons.org/qatarairways/${SI}`, style: { fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', fontSize: 20 } },
    { name: 'Kraken',        src: '/ss-deck-assets/partners/kraken.png',       style: { fontWeight: 700, letterSpacing: '-0.2px', fontSize: 28 } },
  ];

  // Investors mirror the SS deck strip (KASZEK, DST GLOBAL, TIGERGLOBAL,
  // andreessen.horowitz, monashees+, Global PayTech Ventures). Logos load
  // from /ss-deck-assets/trusted/* and fall back to text wordmarks on 404.
  const investors = [
    { name: 'KASZEK',                  src: '/ss-deck-assets/trusted/kaszek.png' },
    { name: 'DST GLOBAL',              src: '/ss-deck-assets/trusted/dst-global.png' },
    { name: 'TIGERGLOBAL',             src: '/ss-deck-assets/trusted/tiger-global.png' },
    { name: 'andreessen.horowitz',     src: '/ss-deck-assets/trusted/andreessen-horowitz.png' },
    { name: 'monashees+',              src: '/ss-deck-assets/trusted/monashees.png' },
    // Global PayTech is a stacked wordmark (icon-on-top), so it reads smaller
    // than the rest at the default 26px cap. Mirror the SS deck override —
    // give it more vertical room so it matches the optical weight of the row.
    { name: 'Global PayTech Ventures', src: '/ss-deck-assets/trusted/global-paytech-ventures.png',
      imgStyle: { height: 44, maxWidth: 170 } },
  ];

  return (
    <div className="slide theme-light" data-screen-label="08 Trusted By">
      <SlideChrome section={window.tr(lang, 'common.why_yuno_trust')} pageNum={9} />

      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 20, minHeight: 0 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: 36, flexShrink: 0 }}>
          <h2 className="t-title t-title-m" style={{ maxWidth: '62%' }}>
            <span className="accent">{window.tr(lang, 's08.title_accent')}</span>{window.tr(lang, 's08.title_tail_l1')}<br/>{window.tr(lang, 's08.title_tail_l2')}
          </h2>
          <p className="t-body" style={{ maxWidth: '34%', textAlign: 'right', color: 'var(--ink-secondary)' }}>
            {window.tr(lang, 's08.subtitle_lead')}<strong style={{ color: 'var(--ink-strong)', fontWeight: 700 }}>{window.tr(lang, 's08.subtitle_strong')}</strong>{window.tr(lang, 's08.subtitle_tail')}
          </p>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: 10, flexShrink: 0 }}>
          <span style={{
            width: 5, height: 5, borderRadius: '50%',
            background: 'linear-gradient(135deg, var(--accent) 0%, var(--accent-pale) 100%)',
            boxShadow: '0 0 6px rgba(62,79,224,0.6)',
          }} />
          <span style={{
            fontSize: 14, fontWeight: 700, letterSpacing: '1.8px',
            textTransform: 'uppercase', color: 'var(--accent-deep)',
          }}>{window.tr(lang, 's08.merchants_label')}</span>
          <BeamRule delay={1.5} />
        </div>

        {/* Logo grid — 5 × 3 (15 tiles) mirrors deck.yuno.tools's Trust slide.
            Same maxHeight as before so the investor strip stays anchored. */}
        <div className="stagger" style={{
          flex: 1, display: 'grid',
          gridTemplateColumns: 'repeat(5, 1fr)', gridTemplateRows: 'repeat(3, 1fr)',
          gap: 14, minHeight: 0, maxHeight: 620,
          '--stagger-base': '0.2s', '--stagger-step': '0.04s',
        }}>
          {clients.map((c) => <TrustedMerchantTile key={c.name} c={c} />)}
        </div>

        {/* Backed by strip */}
        <div style={{ flexShrink: 0, display: 'flex', flexDirection: 'column', gap: 10 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <span style={{
              width: 5, height: 5, borderRadius: '50%',
              background: 'var(--accent-pale)',
            }} />
            <span className="t-label" style={{ color: 'var(--ink-muted)' }}>{window.tr(lang, 's08.backed_by')}</span>
            <BeamRule delay={4} base="linear-gradient(90deg, rgba(189,195,246,0.45) 0%, rgba(189,195,246,0) 100%)" />
          </div>
          <div className="card-nova" style={{
            display: 'flex', justifyContent: 'space-between', alignItems: 'center',
            gap: 32, padding: '18px 28px',
          }}>
            {investors.map(inv => <InvestorMark key={inv.name} inv={inv} />)}
          </div>
        </div>
      </div>
    </div>
  );
}

// =============================================================================
// Export
// =============================================================================
Object.assign(window, {
  Slide01Cover, Slide02Agenda, Slide03ContextSection,
  Slide04ClientStack, Slide05Geography,
  Slide06WhyYunoSection, Slide07YunoOverview, Slide08Trust,
  // shared (slides-02 reuses SectionDivider for slides 09 + future)
  SectionDivider,
});
